version: "3"

services:

  app:
    image: cbsanjaya/laravel:app
    volumes:
      - ${APP_SRC}:/home/laravel/web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - cache
    networks:
      - backend
      - frontend
