version: "3"

services:

  app:
    build:
      context: ./php-fpm
    volumes:
      - ${APP_SRC}:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    depends_on:
      - db
      - cache
    networks:
      - backend

  web:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=app
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ${APP_SRC}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - frontend
      - backend

  db:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  dbadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - dbadmin:/sessions
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db
    networks:
      - frontend
      - backend
    
  cache:
    image: redis:alpine
    volumes:
      - cache:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db:
  cache:
  dbadmin:
